# Generated by Django 5.0 on 2026-01-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='current_phase',
            field=models.CharField(choices=[('introduction', '導入'), ('sharing', '共有'), ('discussion', '議論'), ('summary', 'まとめ')], default='introduction', max_length=20),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
