# Generated by Django 5.0 on 2026-01-16 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0002_meeting_current_phase_meeting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='use_facilitator',
            field=models.BooleanField(default=False, help_text='AIファシリテーター機能を有効にする'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='use_timekeeper',
            field=models.BooleanField(default=True, help_text='タイムキーパー機能を有効にする'),
        ),
    ]
