# Generated by Django 5.0 on 2026-01-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0003_meeting_use_facilitator_meeting_use_timekeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_ended',
            field=models.BooleanField(default=False, help_text='会議が終了したかどうか'),
        ),
    ]
