# Generated by Django 5.0 on 2026-01-20 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0005_transcriptcomment_transcriptmark_transcriptstamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='AI', max_length=100)),
                ('personality', models.CharField(choices=[('idea', '💡 新たなアイディアを提案'), ('facilitator', '🎯 議論を促進'), ('cheerful', '😊 明るい'), ('negative', '😟 ネガティブ'), ('angry', '😠 怒りっぽい')], default='facilitator', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_members', to='minutes.meeting')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIMemberResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('timestamp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='minutes.aimember')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ai_responses', to='minutes.transcript')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
