# Generated by Django 5.0 on 2026-01-23 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0006_aimember_aimemberresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimemberresponse',
            name='triggered_by_ai_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_ai_responses_chain', to='minutes.aimemberresponse'),
        ),
    ]
