# Generated by Django 5.0 on 2026-01-26 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0008_debate_debatestatement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DebateStatement',
        ),
        migrations.DeleteModel(
            name='Debate',
        ),
    ]
