# Generated by Django 5.0 on 2026-01-27 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0009_remove_debate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aimember',
            index=models.Index(fields=['meeting', 'is_active'], name='minutes_aim_meeting_b98856_idx'),
        ),
        migrations.AddIndex(
            model_name='aimemberresponse',
            index=models.Index(fields=['ai_member', 'timestamp'], name='minutes_aim_ai_memb_0b2447_idx'),
        ),
        migrations.AddIndex(
            model_name='transcript',
            index=models.Index(fields=['meeting', 'timestamp'], name='minutes_tra_meeting_3bb6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptcomment',
            index=models.Index(fields=['transcript'], name='minutes_tra_transcr_8c98ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptmark',
            index=models.Index(fields=['transcript'], name='minutes_tra_transcr_a87b50_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptstamp',
            index=models.Index(fields=['transcript'], name='minutes_tra_transcr_d4f6ba_idx'),
        ),
    ]
