# Generated by Django 5.0 on 2026-01-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0010_aimember_minutes_aim_meeting_b98856_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimember',
            name='voicevox_pitch',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='aimember',
            name='voicevox_speaker_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aimember',
            name='voicevox_speed',
            field=models.FloatField(default=1.0),
        ),
    ]
