# Generated by Django 5.0 on 2026-02-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0011_add_voicevox_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimember',
            name='voicevox_style_id',
            field=models.IntegerField(default=0),
        ),
    ]
