# Generated by Django 5.0 on 2026-02-02 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minutes', '0012_add_voicevox_style_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='include_ai_in_summary',
            field=models.BooleanField(default=False, help_text='要約にAIの発言を含めるかどうか'),
        ),
    ]
