# Generated by Django 5.0 on 2026-01-26 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_type', models.CharField(choices=[('logical', '論理的'), ('creative', '創造的'), ('diplomatic', '外交的'), ('aggressive', '攻撃的')], default='logical', max_length=50)),
                ('status', models.CharField(choices=[('setup', 'セットアップ'), ('debating', 'ディベート中'), ('completed', '完了')], default='setup', max_length=20)),
                ('first_speaker', models.CharField(choices=[('user', 'ユーザー'), ('ai', 'AI')], default='user', max_length=10)),
                ('winner', models.CharField(blank=True, choices=[('user', 'ユーザー'), ('ai', 'AI'), ('draw', '引き分け')], max_length=10, null=True)),
                ('judgment_text', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebateStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('user', 'ユーザー'), ('ai', 'AI')], max_length=10)),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='debate.debate')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('debate', 'order')},
            },
        ),
    ]
