# Generated by Django 5.0 on 2026-01-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debate',
            name='max_turns',
            field=models.IntegerField(default=3),
        ),
    ]
