# Generated by Django 5.0 on 2026-01-27 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_debate_max_turns'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debate',
            index=models.Index(fields=['status', '-created_at'], name='debate_deba_status_9262f9_idx'),
        ),
        migrations.AddIndex(
            model_name='debatestatement',
            index=models.Index(fields=['debate', 'order'], name='debate_deba_debate__514881_idx'),
        ),
    ]
